name: Run Tests

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup tinyproxy
        run: |
          sudo apt-get update
          sudo apt-get install -y tinyproxy
          echo "Port 8888" | sudo tee /tmp/tinyproxy.conf
          echo "Listen 127.0.0.1" | sudo tee -a /tmp/tinyproxy.conf
          echo "Timeout 600" | sudo tee -a /tmp/tinyproxy.conf
          sudo tinyproxy -c /tmp/tinyproxy.conf -d &
          sleep 2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install dependencies
        run: npm ci --safe-chain-logging=verbose

      - name: Run tests
        run: |
          # Ensure tinyproxy is fully started
          sleep 2 
          npm test --safe-chain-logging=verbose
        env:
          HTTP_PROXY: http://127.0.0.1:8888
          HTTPS_PROXY: http://127.0.0.1:8888
